import {
  ArrowLeftRight,
  ArrowRight,
  Calendar,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  Coins,
  Copy,
  Download,
  FileText,
  Filter,
  Folder,
  Info,
  LayoutDashboard,
  Lock,
  Pencil,
  Plus,
  RotateCcw,
  Search,
  Snowflake,
  TriangleAlert,
  Wallet,
  X,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

/** Every kebab-case icon name of Design/components/core/Icon.jsx's `ICON_PATHS`, mapped onto its lucide-react component. */
export const CONSOLE_ICONS: Record<string, LucideIcon> = {
  'layout-dashboard': LayoutDashboard,
  folder: Folder,
  wallet: Wallet,
  'arrow-left-right': ArrowLeftRight,
  coins: Coins,
  'file-text': FileText,
  search: Search,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  'chevrons-left': ChevronsLeft,
  'chevrons-right': ChevronsRight,
  x: X,
  copy: Copy,
  check: Check,
  'triangle-alert': TriangleAlert,
  plus: Plus,
  'arrow-right': ArrowRight,
  info: Info,
  'rotate-ccw': RotateCcw,
  filter: Filter,
  pencil: Pencil,
  lock: Lock,
  calendar: Calendar,
  download: Download,
  snowflake: Snowflake,
};
